#!/bin/sh

# this makes it work in Ubuntu
xhost +
## you might need to append the TTY you are working on
xinit

wmname EXWM

# Set fallback cursor
xsetroot -cursor_name left_ptr

# Finally launch emacs and enable exwm
exec dbus-launch --exit-with-session emacs
