#!/bin/sh

# this makes it work in Ubuntu
xhost +
## you might need to append the TTY you are working on
xinit

# Remap caps lock to left control. This is not strictly speaking
# exwm related, but it's handy
setxkbmap -option 'ctrl:no caps'
wmname EXWM

# Set fallback cursor
xsetroot -cursor_name left_ptr

# Finally launch emacs and enable exwm
exec dbus-launch --exit-with-session emacs --eval "(exwm-enable)"
