## Makefile --- Spacemacs org tests
##
## Copyright (c) 2012-2021 Sylvain Benner & Contributors
##
## Author: smile13241324 <smile13241324@gmail.com>
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

TEST_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

LOAD_FILES = init.el
UNIT_TEST_FILES =
FUNC_TEST_FILES = \
org-export-ftest.el

include ../../spacemacs.mk
