#+TITLE: dtrt-indent layer

#+TAGS: layer|misc

Space-macs layer wrapping the e-macs package [[https://github.com/jscheid/dtrt-indent][dtrt-indent]].
This package enables automatic detection and switching of indentation style to match the current file.
See the [[https://github.com/jscheid/dtrt-indent][dtrt-indent]] repo for more details.

* Table of Contents                     :TOC_5_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]

* Description
This is a simple layer wrapping the dtrt-indent e-macs package for automatic detection and switching of indentation style.

It is automatically enabled using the method [[https://github.com/syl20bnr/space-macs/issues/3203#issuecomment-264175032][suggested here]].

** Features:
- Indentation style detection and automatic configuration to match file in open buffer.

* Install
To use this configuration layer, add it to your =~/.space-macs=. You will need to
add =dtrt-indent= to the existing =dotspace-macs-configuration-layers= list in this
file.


