#+TITLE: Mu4e layer
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../../css/readtheorg.css" />

* Table of Contents                                         :TOC_4_org:noexport:
 - [[Install][Install]]
 - [[Commands][Commands]]
 - [[Configuration][Configuration]]
   - [[Maildirs extension][Maildirs extension]]
   - [[Multiple Accounts][Multiple Accounts]]
   - [[Example configuration][Example configuration]]
 - [[See also][See also]]

* Install
In order to use this layer you must install mu and mu4e separately. Typically
mu4e will be bundled with mu (this is the case on many Linux distributions).

If the installation directory of mu4e is not in Emacs’ load path, you can set
the layer variable =mu4e-installation-path=, for example:

#+begin_src emacs-lisp
  (setq-default dotspacemacs-configuration-layers
                '((mu4e :variables
                        mu4e-installation-path "/usr/share/emacs/site-lisp")))
#+end_src

Then add this layer to your =~/.spacemacs=. You will need to add =mu4e= to the
existing =dotspacemacs-configuration-layers= list in this file.

* Commands

| Keybinding | Command    |
|------------+------------|
| SPC a M    | Start mu4e |

* Configuration
Configuration varies too much to give precise instructions.  What follows is one
example configuration.  Refer to mu4e's manual for more detailed configuration
instructions.

** Maildirs extension
The maildirs extension adds a list of all your maildirs to the main mu4e view
that by default shows the unread and total mail counts for all your mail under
your base mail directory.

This extension is enabled by default, you can deactivate (and uninstall) it by
adding the package == to your dotfile variable =dotspacemacs-excluded-packages=.

** Multiple Accounts
With mu 0.9.16, mu4e comes with a native contexts feature for managing multiple accounts.
The following example is taken from the manual:

#+BEGIN_SRC emacs-lisp
  (setq mu4e-contexts
    `( ,(make-mu4e-context
    :name "Private"
    :enter-func (lambda () (mu4e-message "Switch to the Private context"))
    ;; leave-func not defined
    :match-func (lambda (msg)
      (when msg
        (mu4e-message-contact-field-matches msg
          :to "aliced@home.example.com")))
    :vars '(  ( user-mail-address      . "aliced@home.example.com"  )
       ( user-full-name     . "Alice Derleth" )
       ( mu4e-compose-signature .
         (concat
           "Alice Derleth\n"
           "Lauttasaari, Finland\n"))))
       ,(make-mu4e-context
    :name "Work"
    :enter-func (lambda () (mu4e-message "Switch to the Work context"))
    ;; leave-fun not defined
    :match-func (lambda (msg)
      (when msg
        (mu4e-message-contact-field-matches msg
          :to "aderleth@miskatonic.example.com")))
    :vars '(  ( user-mail-address      . "aderleth@miskatonic.example.com" )
       ( user-full-name     . "Alice Derleth" )
       ( mu4e-compose-signature .
         (concat
           "Prof. Alice Derleth\n"
           "Miskatonic University, Dept. of Occult Sciences\n"))))))

  ;; set `mu4e-context-policy` and `mu4e-compose-policy` to tweak when mu4e should
  ;; guess or ask the correct context, e.g.

  ;; start with the first (default) context;
  ;; default is to ask-if-none (ask when there's no context yet, and none match)
  ;; (setq mu4e-context-policy 'pick-first)

  ;; compose with the current context is no context matches;
  ;; default is to ask
  ;; '(setq mu4e-compose-context-policy nil)
#+END_SRC

** Example configuration
#+BEGIN_SRC emacs-lisp
  ;;; Set up some common mu4e variables
  (setq mu4e-maildir "~/.mail"
        mu4e-trash-folder "/Trash"
        mu4e-refile-folder "/Archive"
        mu4e-get-mail-command "mbsync -a"
        mu4e-update-interval nil
        mu4e-compose-signature-auto-include nil
        mu4e-view-show-images t
        mu4e-view-show-addresses t)

  ;;; Mail directory shortcuts
  (setq mu4e-maildir-shortcuts
        '(("/gmail/INBOX" . ?g)
          ("/college/INBOX" . ?c)))

  ;;; Bookmarks
  (setq mu4e-bookmarks
        `(("flag:unread AND NOT flag:trashed" "Unread messages" ?u)
          ("date:today..now" "Today's messages" ?t)
          ("date:7d..now" "Last 7 days" ?w)
          ("mime:image/*" "Messages with images" ?p)
          (,(mapconcat 'identity
                       (mapcar
                        (lambda (maildir)
                          (concat "maildir:" (car maildir)))
                        mu4e-maildir-shortcuts) " OR ")
           "All inboxes" ?i)))
#+END_SRC

* See also
Refer to the official mu and mu4e documentation for additional info.

- [[http://www.djcbsoftware.nl/code/mu/mu4e/index.html][mu4e Manual]]
