#!/bin/bash
# Cleanup script for Docker
#
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2017 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

apt-get autoremove
rm -rf /tmp/* /var/lib/apt/lists/* /root/.cache/*
