#+TITLE: Deft layer

* Table of Contents                     :TOC_4_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
  - [[#layer][Layer]]
  - [[#configuration][Configuration]]
- [[#key-bindings][Key bindings]]

* Description
This layer adds a search driven note taking system into Spacemacs.

** Features:
- Browsing and creating notes with a powerfull search function via [[http://jblevins.org/projects/deft/][Deft]].
- Integration of =org-mode= as note editor.
- Configurable list of extensions to recognize as notes.

* Install
** Layer
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =deft= to the existing =dotspacemacs-configuration-layers= list in this
file.

** Configuration
By default deft tries to put notes in =~/.deft= but you can change
this in your =dotspacemacs/user-config= function:

#+BEGIN_SRC emacs-lisp
  (setq deft-directory "~/Dropbox/notes")
#+END_SRC

By default =Deft= uses filenames for note titles and =org-mode= for editing.
The default extension for new notes is =org=. However also =md= and =txt=
files are recognized as notes. Which extensions are used for notes discovery
can be configured in your =dotfile=:

#+BEGIN_SRC emacs-lisp
  (setq deft-extensions '("org" "md" "txt"))
#+END_SRC

Just add or substitute your preferred extension.

* Key bindings

| Key binding | Description                      |
|-------------+----------------------------------|
| ~SPC a n~   | Open Deft (works globally)       |
| ~SPC m c~   | Clear deft filter                |
| ~SPC m d~   | Delete selected note             |
| ~SPC m i~   | Toggle to regex search           |
| ~SPC m n~   | Create new file with filter text |
| ~SPC m N~   | Create new file named            |
| ~SPC m o~   | Deft open file in other window   |
| ~SPC m r~   | Rename selected note             |
| ~SPC m q~   | quit deft window                 |
