#+TITLE: Pandoc layer

#+TAGS: layer|tool

* Table of Contents                     :TOC_4_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
  - [[#layer][Layer]]
  - [[#pandoc][Pandoc]]
- [[#usage][Usage]]
- [[#key-bindings][Key bindings]]

* Description
This layer adds support for [[http://pandoc.org/][Pandoc]].

Pandoc is a universal document converter. It makes it easy to e.g. convert a
Markdown file to org mode or vice versa. It can also export your text to PDF or
DOCX.

** Features:
- Mode independent document conversions via =global pandoc menu=
- =Org-export= integration via [[https://github.com/kawabata/ox-pandoc][ox-pandoc]]

* Install
** Layer
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =pandoc= to the existing =dotspacemacs-configuration-layers= list in this
file.

** Pandoc
To use the mode please [[http://pandoc.org/installing.html][install]] pandoc first.

* Usage
For a full list of possible conversions see the [[http://pandoc.org/][Pandoc documentation]].
An explanation of all the options offered by =pandoc-mode= can be found at the
[[http://joostkremers.github.io/pandoc-mode/][Pandoc-mode website]].

* Key bindings

| Key binding | Description                     |
|-------------+---------------------------------|
| ~SPC P /~   | Start pandoc-mode and open menu |
