#+TITLE: Pandoc layer
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../../css/readtheorg.css" />

* Table of Contents                                         :TOC_4_org:noexport:
 - [[Description][Description]]
 - [[Install][Install]]
   - [[Layer][Layer]]
   - [[Pandoc][Pandoc]]
 - [[Usage][Usage]]
 - [[Key Bindings][Key Bindings]]

* Description

This layer adds support for [[http://johnmacfarlane.net/pandoc][Pandoc]].

Pandoc is a universal document converter. It makes it easy to e.g. convert a
Markdown file to org mode or vice versa. It can also export your text to PDF or
DOCX.

This layer automatically install an org exporter using the [[https://github.com/kawabata/ox-pandoc][ox-pandoc]].

* Install

** Layer

To use this contribution add it to your =~/.spacemacs=

#+BEGIN_SRC emacs-lisp
  (setq-default dotspacemacs-configuration-layers '(pandoc))
#+END_SRC

** Pandoc

To use the mode please [[http://pandoc.org/installing.html][install]] pandoc first.

* Usage

For a full list of possible conversions see the [[http://johnmacfarlane.net/pandoc][Pandoc documentation]].
An explanation of all the options offered by =pandoc-mode= can be found at the
[[http://joostkremers.github.io/pandoc-mode][Pandoc-mode website]].

* Key Bindings

| Key Binding | Description                     |
|-------------+---------------------------------|
| ~SPC P /~   | Start pandoc-mode and open menu |
