;;; helm-ag-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-ag.el

(autoload 'helm-ag-pop-stack "helm-ag" "\
Not documented." t)
(autoload 'helm-ag-clear-stack "helm-ag" "\
Not documented." t)
(autoload 'helm-ag-this-file "helm-ag" "\
Do ag with in this file with QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-ag "helm-ag" "\
Do ag with in BASEDIR and with QUERY.

(fn &optional BASEDIR QUERY)" t)
(autoload 'helm-do-ag-this-file "helm-ag" "\
Not documented, QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag "helm-ag" "\
Not documented, BASEDIR, TARGETS, DEFAULT-INPUT.

(fn &optional BASEDIR TARGETS DEFAULT-INPUT)" t)
(autoload 'helm-ag-project-root "helm-ag" "\
Not documented, QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag-project-root "helm-ag" "\
Not documented, QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-ag-buffers "helm-ag" "\
Not documented, QUERY.

(fn &optional QUERY)" t)
(autoload 'helm-do-ag-buffers "helm-ag" "\
Not documented, QUERY.

(fn &optional QUERY)" t)
(register-definition-prefixes "helm-ag" '("helm-"))

;;; End of scraped data

(provide 'helm-ag-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-ag-autoloads.el ends here
