---
# TravisCI YAML file
language: generic
sudo: false
branches:
  only:
  - master
  - develop
env:
  matrix:
  - EVM_EMACS=emacs-25.3-travis
  global:
  - secure: "M8NF1Uw7VGkLdNmWiUF4T+VOJXwN8KCKVQb45/BWVpGm88Rcfom/9bxRTUme8VYuzIavph32QF+P9KyhX8aj2p2FMItNnxiEySzap5UrLrNiwB6ZxbQglMJj0yMQKASynNBai9KKI7mYlsM5jRpFJ9OSgj7Ko00RIFpO3EpJ+kE="
  - BOT_NAME=emacspace
  - BOT_EMAIL=emacspace@gmail.com
script: ".travisci/test.sh"
deploy:
  skip_cleanup: true
  provider: script
  script: ".travisci/pub.sh"
  on:
    all_branches: true
    condition: $TRAVIS_SECURE_ENV_VARS = true
