---
# TravisCI YAML file
language: generic
sudo: false
branches:
  only:
  - master
  - develop
before_install:
- curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw
  > /tmp/x.sh && source /tmp/x.sh
- evm install $EVM_EMACS --use --skip
env:
  matrix:
  - TESTS=core EVM_EMACS=emacs-24.4-travis
  - TESTS=core EVM_EMACS=emacs-24.5-travis
  - TESTS=core EVM_EMACS=emacs-25.2-travis
  - TESTS=core EVM_EMACS=emacs-git-snapshot-travis
  - FORMAT=all EVM_EMACS=emacs-25.2-travis
  global:
  - secure: "M8NF1Uw7VGkLdNmWiUF4T+VOJXwN8KCKVQb45/BWVpGm88Rcfom/9bxRTUme8VYuzIavph32QF+P9KyhX8aj2p2FMItNnxiEySzap5UrLrNiwB6ZxbQglMJj0yMQKASynNBai9KKI7mYlsM5jRpFJ9OSgj7Ko00RIFpO3EpJ+kE="
  - BOT_NAME=emacspace
  - BOT_EMAIL=emacspace@gmail.com
matrix:
  fast_finish: true
  allow_failures:
  - env: TESTS=core EVM_EMACS=emacs-git-snapshot-travis
  - env: FORMAT=all EVM_EMACS=emacs-25.2-travis
script: ".travisci/test.sh"
deploy:
  skip_cleanup: true
  provider: script
  script: ".travisci/pub.sh"
  on:
    all_branches: true
    condition: $FORMAT = all
