---
# TravisCI YAML file
language: generic
sudo: required
services:
  - docker
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: "M8NF1Uw7VGkLdNmWiUF4T+VOJXwN8KCKVQb45/BWVpGm88Rcfom/9bxRTUme8VYuzIavph32QF+P9KyhX8aj2p2FMItNnxiEySzap5UrLrNiwB6ZxbQglMJj0yMQKASynNBai9KKI7mYlsM5jRpFJ9OSgj7Ko00RIFpO3EpJ+kE="
  - BOT_NAME=emacspace
  - BOT_EMAIL=emacspace@gmail.com
  - SPACEMACS_REPO_SLUG="syl20bnr/spacemacs"
before_script:
  - docker pull jare/spacetools:latest
script:
  - git checkout "${TRAVIS_BRANCH}" && .travisci/pub_prep.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ".travisci/pub_org.sh"
    on:
      branch: develop
      # Deploy only if we are in the official repo and
      # the local revision matches origin's head
      condition: $TRAVIS_REPO_SLUG = $SPACEMACS_REPO_SLUG && $(git remote update) && $(git rev-parse '@') = $(git rev-parse '@{u}') && $HAS_DOC_FIXES = true
  - provider: script
    skip_cleanup: true
    script: ".travisci/pub_html.sh"
    on:
      all_branches: true
      # Deploy only if we are in the official repo and
      # the local revision matches origin's head
      condition: $TRAVIS_REPO_SLUG = $SPACEMACS_REPO_SLUG && $(git remote update) && $(git rev-parse '@') = $(git rev-parse '@{u}')
