---
# TravisCI YAML file
language: generic
sudo: required
services:
  - docker
branches:
  only:
  - master
  - develop
env:
  matrix:
  - EVM_EMACS=emacs-26.1-travis
  global:
  - secure: "M8NF1Uw7VGkLdNmWiUF4T+VOJXwN8KCKVQb45/BWVpGm88Rcfom/9bxRTUme8VYuzIavph32QF+P9KyhX8aj2p2FMItNnxiEySzap5UrLrNiwB6ZxbQglMJj0yMQKASynNBai9KKI7mYlsM5jRpFJ9OSgj7Ko00RIFpO3EpJ+kE="
  - BOT_NAME=emacspace
  - BOT_EMAIL=emacspace@gmail.com
before_script:
- docker pull jare/spacetools:latest
script: ".travisci/test.sh"
before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      .travisci/pub_prep.sh
    fi
deploy:
  - provider: script
    skip_cleanup: true
    script: ".travisci/pub_org.sh"
    on:
      all_branches: true
      condition: $TRAVIS_REPO_SLUG = "syl20bnr/spacemacs"
  - provider: script
    skip_cleanup: true
    script: ".travisci/pub_html.sh"
    on:
      all_branches: true
      condition: $TRAVIS_REPO_SLUG = "syl20bnr/spacemacs"
