branches:
  only:
    - master
    - develop

before_install:
  sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get -qq update &&
  sudo apt-get -qq -f install &&
  sudo apt-get -qqy install emacs-snapshot;

script:
  cd ~/.emacs.d/core
  make test