---
# TravisCI YAML file
language: generic
sudo: false
branches:
 only:
 - master
 - develop
before_install:
- curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw
  > /tmp/x.sh && source /tmp/x.sh
- evm install $EVM_EMACS --use --skip
env:
 matrix:
 - TESTS=core EVM_EMACS=emacs-24.4-travis
 - TESTS=core EVM_EMACS=emacs-24.5-travis
 - TESTS=core EVM_EMACS=emacs-25.2-travis
 - TESTS=core EVM_EMACS=emacs-git-snapshot-travis
 - TESTS=doc EVM_EMACS=emacs-24.4-travis
 - TESTS=doc EVM_EMACS=emacs-24.5-travis
 - TESTS=doc EVM_EMACS=emacs-25.2-travis
 - TESTS=doc EVM_EMACS=emacs-git-snapshot-travis
 - PUBLISH=spacemacs.org EVM_EMACS=emacs-25.2-travis
 - PUBLISH=develop.spacemacs.org EVM_EMACS=emacs-25.2-travis
 global:
 - secure: "M8NF1Uw7VGkLdNmWiUF4T+VOJXwN8KCKVQb45/BWVpGm88Rcfom/9bxRTUme8VYuzIavph32QF+P9KyhX8aj2p2FMItNnxiEySzap5UrLrNiwB6ZxbQglMJj0yMQKASynNBai9KKI7mYlsM5jRpFJ9OSgj7Ko00RIFpO3EpJ+kE="
 - BOT_NAME=emacspace
 - BOT_EMAIL=emacspace@gmail.com
matrix:
 fast_finish: true
 allow_failures:
 - env: TESTS=core EVM_EMACS=emacs-git-snapshot-travis
 - env: TESTS=doc EVM_EMACS=emacs-24.4-travis
 - env: TESTS=doc EVM_EMACS=emacs-24.5-travis
 - env: TESTS=doc EVM_EMACS=emacs-25.2-travis
 - env: TESTS=doc EVM_EMACS=emacs-git-snapshot-travis
 - env: PUBLISH=spacemacs.org EVM_EMACS=emacs-25.2-travis
 - env: PUBLISH=develop.spacemacs.org EVM_EMACS=emacs-25.2-travis
script: "./.travis-build.sh"
