#+TITLE: Spacemacs Community

* Table of Contents                     :TOC_5_gh:noexport:
- [[#philosophy][Philosophy]]
  - [[#for-contributors][For Contributors]]
  - [[#for-users][For Users]]
- [[#moderation][Moderation]]
  - [[#guidelines][Guidelines]]
    - [[#people][People]]
    - [[#issues][Issues]]
    - [[#pull-requests-and-commmits][Pull requests and Commmits]]
    - [[#messages][Messages]]
  - [[#interpretation][Interpretation]]
  - [[#collaborators-privacy][Collaborators privacy]]
  - [[#maintainer][Maintainer]]
  - [[#log][Log]]

* Philosophy
** For Contributors
- This community is a community of hackers based on meritocracy and
  volunteering. Hackers strive for excellence to make the world a better place,
  so does the Spacemacs community.
- Be good in what you bring to the project be it code, documentation, typo
  fixes, art, humor, ideas, project management, web design, assurance quality,
  mentorship, you name it! We like to award achievements to people making a
  difference in a wide variety of domains and occasions, [[https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#special-titles][see it for yourself]].
  Why not you? Make it happen, make history!
- Think you are not good enough? Find support and mentors by chatting on Gitter
  with fellow Spacemacs users or just open an issue on GitHub, you will find
  help to fulfil your desire of contribution. We welcome anyone with good
  intentions.
- In a nutshell: Be good, positive and/or with good intentions and focused on
  the project.

** For Users
- Any question related to the project is welcomed and encouraged, the worst
  thing that can happen is that we redirect you to the documentation.
- The majority of the interactions with the community happens on GitHub via
  issues and on Gitter via the official Spacemacs channel. There is also an
  active official twitter account =spacemacs=.
- Any opinion on the project is valorized given it is constructive.

* Moderation
We want the community to be judged based on its moderation actions instead of
telling people how to behave. The golden rules of the community are to have good
intentions and stay focused on the project, for anything else that requires
moderation any future user or contributor can refer to this section to know
about our past moderation actions. So readers won’t find any example or
definition of what collaborators judge offending or outrageous, instead they
will find at the end of this section a log of all major moderation actions taken
by the collaborators since the beginning of the project which started officially
in August 2014. It should allow you to decide whether or not you want to be part
of this community. If you are not convinced then be assured that the only evil
part in Spacemacs is the evil mode :-)

** Guidelines
These guidelines apply to all collaborators of the project, namely @syl20bnr,
@TheBB, @d12frosted and @bmag.

*** People
- Collaborators cannot ban any GitHub user from the repository but they can ban
  users from the official Gitter channel.
- A user can be banned if and only if all the collaborators agree to do so.
- The reasons of the ban are mentioned in the moderation actions log (see
  below).

*** Issues
- Issues can be locked if their contents are judged _inappropriate_, _offending_
  or if they deviate _dangerously_ from the project.

*** Pull requests and Commmits
- Collaborators can push to the repository without making a PR.
- PR can be rejected. Rejected PR always go with a reason explicitly written
  when closing the PR.
- Commits can be reverted if they compromise the stability of the project. The
  reason is contained in the commit comments.
- Pull request are also issues, thus issue guidelines also apply to pull
  requests.

*** Messages
- Only the form of a message can be edited, not its meaning, except if this
  meaning is _outrageous_.
- Moderators can add information to a message to improve its accuracy without
  altering its meaning,
- Any edition of a message is logged in the =edits log= located at the end of
  the edited message with the following format:

  #+BEGIN_EXAMPLE
    EDIT: [@moderator] action (reason: xxx)
  #+END_EXAMPLE

- The reason is added only when needed (for instance we won’t add a reason for
  formatting edits)

** Interpretation
Words used in these guidelines like _good_, _inappropriate_, _offending_,
_dangerously_ and _outrageous_ are used without any explanation, their meanings
and interpretations are left solely to the discretion of the collaborators who
are educated persons working in the interest of the community.

** Collaborators privacy
Life and actions of collaborators outside of the project (i.e. outside of the
Spacemacs GitHub repository, official Spacemacs Gitter channels and Twitter
official Spacemacs account timeline) are completely detached from their
activities and roles in the project. They are free to express any opinion on the
project or any other subjects and those opinions cannot be used to compromise
their roles in the project as long as they follow the moderation guidelines with
good intentions.

** Maintainer
- The maintainer @syl20bnr as a BDFL is free to demote a collaborator in extreme
  situations.
- When there is no consensus on a subject, the BDFL can decide to impose his
  view on the subject.

** Log
For transparency and future reference any major moderation actions are recorded
here. As of Sunday, April 10th 2016, 7200 issues have been opened and 2 major
moderation actions have been taken:

| Date       | Moderator | Action | Issue | Reason                                                          |
|------------+-----------+--------+-------+-----------------------------------------------------------------|
| 2016/01/27 | syl20bnr  | lock   | #3484 | comments judged to be offending towards the Spacemacs community |
| 2016/01/27 | syl20bnr  | unlock | #3484 | let’s make it happen, i.e. this document                        |
