;;; elfeed-tube-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elfeed-tube.el

 (autoload 'elfeed-tube-fetch "elfeed-tube" "Fetch youtube metadata for Youtube video or Elfeed entry ENTRIES." t nil)
(register-definition-prefixes "elfeed-tube" '("elfeed-tube-"))


;;; Generated autoloads from elfeed-tube-fill.el

 (autoload 'elfeed-tube-fill-feeds "elfeed-tube-fill" "Fetch and add all channel videos for ENTRIES' feeds." t nil)
(register-definition-prefixes "elfeed-tube-fill" '("elfeed-tube--"))


;;; Generated autoloads from elfeed-tube-utils.el

 (autoload 'elfeed-tube-add-feeds "elfeed-tube-utils" "Add youtube feeds to the Elfeed database by QUERIES." t nil)
(register-definition-prefixes "elfeed-tube-utils" '("elfeed-tube-"))

;;; End of scraped data

(provide 'elfeed-tube-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elfeed-tube-autoloads.el ends here
