#+TITLE: Restclient layer
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/readtheorg.css" />

* Table of Contents                                         :TOC_4_org:noexport:
 - [[What is this?][What is this?]]
 - [[Install][Install]]
 - [[Keybindings][Keybindings]]

* What is this?
This is a package that lets you have a REPL-like interface
for http requests. Full documentation and examples can be found in the
package's [[https://github.com/pashky/restclient.el][GitHub Page]].

Also there is an [[http://emacsrocks.com/e15.html][Emacs Rocks!]] episode of it.

* Install
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =restclient= to the existing =dotspacemacs-configuration-layers= list in this
file.

* Keybindings

| Key Binding | Description                                                 |
|-------------+-------------------------------------------------------------|
| ~SPC m s~   | Send and stay in window (pretty-print response if possible) |
| ~SPC m S~   | Send and switch window (pretty-print response if possible)  |
| ~SPC m r~   | Send and stay in window (do not attempt to pretty-print)    |
| ~SPC m R~   | Send and switch window (do not attempt to pretty-print)     |

