;;; org-pdftools-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-pdftools.el

(autoload 'org-pdftools-open "org-pdftools" "\
Function to open org-pdftools LINK.

(fn LINK)")
(autoload 'org-pdftools-store-link "org-pdftools" "\
Store a link to a pdfview/pdfoccur buffer.")
(autoload 'org-pdftools-export "org-pdftools" "\
Export the pdfview LINK with DESCRIPTION for FORMAT from Org files.

(fn LINK DESCRIPTION FORMAT)")
(autoload 'org-pdftools-setup-link "org-pdftools" "\
Set up pdf: links in org-mode.

(fn &optional PREFIX)")
(autoload 'org-pdftools-complete-link "org-pdftools" "\
Use the existing file name completion for file.
Links to get the file name, then ask the user for the page number
and append it. ARG is passed to `org-link-complete-file'.

(fn &optional ARG)")
(register-definition-prefixes "org-pdftools" '("org-pdftools-"))

;;; End of scraped data

(provide 'org-pdftools-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-pdftools-autoloads.el ends here
