;;; spacemacs-purpose-popwin-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from spacemacs-purpose-popwin.el

(register-definition-prefixes "spacemacs-purpose-popwin" '("pupo"))

;;; End of scraped data

(provide 'spacemacs-purpose-popwin-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; spacemacs-purpose-popwin-autoloads.el ends here
