;;; elfeed-org-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elfeed-org.el

(autoload 'elfeed-org "elfeed-org" "\
Hook up rmh-elfeed-org to read the `org-mode' configuration when elfeed is run." t)
(register-definition-prefixes "elfeed-org" '("elfeed-org-" "rmh-elfeed-"))

;;; End of scraped data

(provide 'elfeed-org-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elfeed-org-autoloads.el ends here
