#+TITLE: IBuffer layer
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/readtheorg.css" />

* Table of Contents                                         :TOC_4_org:noexport:
 - [[Description][Description]]
 - [[Install][Install]]
   - [[Layer][Layer]]
   - [[Grouping buffers][Grouping buffers]]
 - [[Key bindings][Key bindings]]

* Description

This layer configures Emacs ibuffer for Spacemacs.

* Install
** Layer
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =ibuffer= to the existing =dotspacemacs-configuration-layers= list in this
file.

** Grouping buffers

Buffers can be grouped by major-modes or projectile projects.
By default buffers are grouped by major-modes.

To change how buffers are grouped set the layer variable
=ibuffer-group-buffers-by= to one of the following supported values:
- =modes= to group buffers by major-modes (default)
- =projects= to group buffers by projectile projects
- =nil= to not group buffers

Example:

#+BEGIN_SRC emacs-lisp
  (setq-default dotspacemacs-configuration-layers '(
    (ibuffer :variables ibuffer-group-buffers-by 'projects)))
#+END_SRC

* Key bindings

| Key Binding | Description       |
|-------------+-------------------|
| ~SPC b B~   | open ibuffer menu |

*Note:* The layer will also replace regular ~C-x C-b~ by ibuffer.
