#!/usr/bin/env bash
## make_patch Creates patch file with the current changes.
##
## Copyright (c) 2014-2021 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

if [[ `git status --porcelain` ]]; then
    git diff HEAD > "/tmp/${PUBLISH}.patch"
fi
