#!/usr/bin/env bash
## PR base check script for CircleCI
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2018 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/space-macs
##
## This file is not part of GNU e-macs.
##
## License: GPLv3

skip_when_branch_update
fail_when_undefined_pr_number

pr_base=$(curl -s "${pr_data_URL}" | jq '.base.ref')
if [[ "${pr_base}" == "\"${dev_b}\"" ]]; then
    echo "You are PRing to the develop branch. This is good."
    exit 0
elif [[ "${pr_base}" == "\"${mst_b}\"" ]]; then
    printf '=%.0s' {1..80}
    printf "\n       ã—(*ï½¥âˆ€ï½¥)ï¼   Thanks for the contribution!  ï¼¼(ï½¥âˆ€ï½¥*)ãƒŽ\n"
    printf '=%.0s' {1..80}
    printf "\n( ï¼¾â—¡ï¼¾)ã£ Please submit your PR against the develop branch.\n"
    echo   "You can read the contribution guidelines at:"
    echo   "https://github.com/syl20bnr/space-macs/blob/develop/CONTRIBUTING.org"
    exit 2
else
    echo_headline  "Your PR has unrecognized base: \"${pr_base}\""
    exit 2
fi


