#!/usr/bin/env bash
## PR base check script for CircleCI
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2018 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

fail_when_undefined_pr_number

if ! pr_json=$(curl -fsSL "${pr_data_URL}"); then
  echo >&2 "Failed to fetch PR data at ${pr_data_URL}"
  exit 2
fi
pr_base=$(jq '.base.ref' <<<"$pr_json")
if [[ "${pr_base}" == "\"develop\"" ]]; then
    echo "You are PRing to the develop branch. This is good."
    exit 0
elif [[ "${pr_base}" == "\"master\"" ]]; then
    printf '=%.0s' {1..80}
    printf "\n       し(*･∀･)／   Thanks for the contribution!  ＼(･∀･*)ノ\n"
    printf '=%.0s' {1..80}
    printf "\n( ＾◡＾)っ Please submit your PR against the develop branch.\n"
    echo   "You can read the contribution guidelines at:"
    echo   "https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org"
    exit 2
else
    echo_headline  "Your PR has unrecognized base: \"${pr_base}\""
    exit 2
fi
