#!/usr/bin/env bash
## PR base check script for CircleCI
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2018 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

skip_for_branch_update

pr_base=$(curl -s "${pr_data_URL}" | jq '.base.ref')
if [[ "${pr_base}" == "\"${dev_b}\"" ]]; then
    echo "You are PRing to the develop branch. This is good."
    exit 0
elif [[ "${pr_base}" == "\"${mst_b}\"" ]]; then
    printf '=%.0s' {1..80}
    printf "\n       し(*･∀･)／   Thanks for the contribution!  ＼(･∀･*)ノ\n"
    printf '=%.0s' {1..80}
    printf "\n( ＾◡＾)っ Please submit your PR against the develop branch.\n"
    echo   "You can read the contribution guidelines at:"
    echo   "https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org"
    exit 2
else
    echo_headline  "Your PR has unrecognized base: \"${pr_base}\""
    exit 2
fi
