#!/usr/bin/env bash
## This script ensures that changelog file was updated.
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2018 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

skip_for_branch_update

if [[ "$CIRCLE_PR_USERNAME" == "${bot_login}" ]]; then
    echo "Fun fact. Bots can't climb stairs or update CHANGELOG.develop"
    exit 0
fi

if grep -q CHANGELOG.develop /tmp/changed_files; then
    echo "CHANGELOG.develop was updated as required"
else
    echo "Please describe your contribution in CHANGELOG.develop"
    echo "if you want it to be mentioned in the release file."
    echo "See CONTRIBUTING.org for the details."
    exit 1
fi
