;;; org-contrib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ob-J.el

(register-definition-prefixes "ob-J" '("obj-" "org-babel-"))


;;; Generated autoloads from ob-abc.el

(register-definition-prefixes "ob-abc" '("org-babel-"))


;;; Generated autoloads from ob-asymptote.el

(register-definition-prefixes "ob-asymptote" '("org-babel-"))


;;; Generated autoloads from ob-coq.el

(register-definition-prefixes "ob-coq" '("coq-program-name" "org-babel-"))


;;; Generated autoloads from ob-csharp.el

(register-definition-prefixes "ob-csharp" '("org-babel-"))


;;; Generated autoloads from ob-ebnf.el

(register-definition-prefixes "ob-ebnf" '("org-babel-"))


;;; Generated autoloads from ob-eukleides.el

(register-definition-prefixes "ob-eukleides" '("org-"))


;;; Generated autoloads from ob-fomus.el

(register-definition-prefixes "ob-fomus" '("org-babel-"))


;;; Generated autoloads from ob-hledger.el

(register-definition-prefixes "ob-hledger" '("org-babel-"))


;;; Generated autoloads from ob-io.el

(register-definition-prefixes "ob-io" '("org-babel-"))


;;; Generated autoloads from ob-ledger.el

(register-definition-prefixes "ob-ledger" '("org-babel-"))


;;; Generated autoloads from ob-mathomatic.el

(register-definition-prefixes "ob-mathomatic" '("org-babel-"))


;;; Generated autoloads from ob-mscgen.el

(register-definition-prefixes "ob-mscgen" '("org-babel-"))


;;; Generated autoloads from ob-oz.el

(register-definition-prefixes "ob-oz" '("org-babel-" "oz-send-string-expression"))


;;; Generated autoloads from ob-picolisp.el

(register-definition-prefixes "ob-picolisp" '("org-babel-"))


;;; Generated autoloads from ob-shen.el

(register-definition-prefixes "ob-shen" '("org-babel-"))


;;; Generated autoloads from ob-stata.el

(register-definition-prefixes "ob-stata" '("org-babel-"))


;;; Generated autoloads from ob-tcl.el

(register-definition-prefixes "ob-tcl" '("org-babel-"))


;;; Generated autoloads from ob-vala.el

(register-definition-prefixes "ob-vala" '("org-babel-"))


;;; Generated autoloads from ob-vbnet.el

(register-definition-prefixes "ob-vbnet" '("org-babel-"))


;;; Generated autoloads from ol-bookmark.el

(register-definition-prefixes "ol-bookmark" '("org-bookmark-"))


;;; Generated autoloads from ol-elisp-symbol.el

(register-definition-prefixes "ol-elisp-symbol" '("org-elisp-symbol-"))


;;; Generated autoloads from ol-git-link.el

(register-definition-prefixes "ol-git-link" '("org-git"))


;;; Generated autoloads from ol-mew.el

(register-definition-prefixes "ol-mew" '("org-mew-"))


;;; Generated autoloads from ol-vm.el

(register-definition-prefixes "ol-vm" '("org-vm-"))


;;; Generated autoloads from ol-wl.el

(register-definition-prefixes "ol-wl" '("org-wl-"))


;;; Generated autoloads from org-annotate-file.el

(autoload 'org-annotate-file "org-annotate-file" "\
Visit `org-annotate-file-storage-file` and add a new annotation section.
The annotation is opened at the new section which will be referencing
the point in the current file." t)
(autoload 'org-annotate-file-show-section "org-annotate-file" "\
Add or show annotation entry in STORAGE-FILE and return the buffer.
The annotation will link to ANNOTATED-BUFFER if specified,
  otherwise the current buffer is used.

(fn STORAGE-FILE &optional ANNOTATED-BUFFER)")
(register-definition-prefixes "org-annotate-file" '("org-annotate-file-"))


;;; Generated autoloads from org-bibtex-extras.el

(register-definition-prefixes "org-bibtex-extras" '("obe-"))


;;; Generated autoloads from org-checklist.el

(register-definition-prefixes "org-checklist" '("org-"))


;;; Generated autoloads from org-choose.el

(register-definition-prefixes "org-choose" '("org-choose-"))


;;; Generated autoloads from org-collector.el

(register-definition-prefixes "org-collector" '("and-rest" "org-"))


;;; Generated autoloads from org-depend.el

(register-definition-prefixes "org-depend" '("org-depend-"))


;;; Generated autoloads from org-effectiveness.el

(register-definition-prefixes "org-effectiveness" '("org-effectiveness-"))


;;; Generated autoloads from org-eldoc.el

(autoload 'org-eldoc-load "org-eldoc" "\
Set up org-eldoc documentation function." t)
(add-hook 'org-mode-hook #'org-eldoc-load)
(register-definition-prefixes "org-eldoc" '("org-eldoc-"))


;;; Generated autoloads from org-eval.el

(register-definition-prefixes "org-eval" '("org-eval-"))


;;; Generated autoloads from org-eval-light.el

(register-definition-prefixes "org-eval-light" '("org-eval-light-"))


;;; Generated autoloads from org-expiry.el

(register-definition-prefixes "org-expiry" '("org-expiry-"))


;;; Generated autoloads from org-interactive-query.el

(register-definition-prefixes "org-interactive-query" '("org-agenda-query-"))


;;; Generated autoloads from org-invoice.el

(register-definition-prefixes "org-invoice" '("org-"))


;;; Generated autoloads from org-learn.el

(register-definition-prefixes "org-learn" '("calculate-new-optimal-factor" "determine-next-interval" "get-optimal-factor" "initial-" "inter-repetition-interval" "modify-" "org-" "set-optimal-factor"))


;;; Generated autoloads from org-license.el

(register-definition-prefixes "org-license" '("org-license-"))


;;; Generated autoloads from org-mac-iCal.el

(register-definition-prefixes "org-mac-iCal" '("omi-" "org-mac-iCal"))


;;; Generated autoloads from org-mairix.el

(register-definition-prefixes "org-mairix" '("org-"))


;;; Generated autoloads from org-panel.el

(register-definition-prefixes "org-panel" '("orgpan-"))


;;; Generated autoloads from org-registry.el

(autoload 'org-registry-show "org-registry" "\
Show Org files where there are links pointing to the current
buffer.

(fn &optional VISIT)" t)
(autoload 'org-registry-visit "org-registry" "\
If an Org file contains a link to the current location, visit
this file." t)
(autoload 'org-registry-initialize "org-registry" "\
Initialize `org-registry-alist'.
If FROM-SCRATCH is non-nil or the registry does not exist yet,
create a new registry from scratch and eval it. If the registry
exists, eval `org-registry-file' and make it the new value for
`org-registry-alist'.

(fn &optional FROM-SCRATCH)" t)
(autoload 'org-registry-insinuate "org-registry" "\
Call `org-registry-update' after saving in Org-mode.
Use with caution.  This could slow down things a bit." t)
(autoload 'org-registry-update "org-registry" "\
Update the registry for the current Org file." t)
(register-definition-prefixes "org-registry" '("org-registry-"))


;;; Generated autoloads from org-screen.el

(register-definition-prefixes "org-screen" '("org-screen"))


;;; Generated autoloads from org-screenshot.el

(autoload 'org-screenshot-take "org-screenshot" "\
Take a screenshot and insert link to it at point, if image
display is already on (see \\[org-toggle-inline-images])
screenshot will be displayed as an image

Screen area for the screenshot is selected with the mouse, left
click on a window screenshots that window, while left click and
drag selects a region. Pressing any key cancels the screen shot

With `C-u' universal argument waits one second after target is
selected before taking the screenshot. With double `C-u' wait two
seconds.

With triple `C-u' wait 3 seconds, and also rings the bell when
screenshot is done, any more `C-u' after that increases delay by
2 seconds

(fn &optional DELAY)" t)
(autoload 'org-screenshot-rotate-prev "org-screenshot" "\
Rotate last screenshot with one of the previously taken
screenshots from the same directory. If DIR is negative, rotate
in the other direction

(fn DIR)" t)
(autoload 'org-screenshot-rotate-next "org-screenshot" "\
Rotate last screenshot with one of the previously taken
screenshots from the same directory. If DIR is negative, rotate
in the other direction

(fn DIR)" t)
(autoload 'org-screenshot-show-unused "org-screenshot" "\
Open A Dired buffer with unused screenshots marked" t)
(register-definition-prefixes "org-screenshot" '("org-screenshot-"))


;;; Generated autoloads from org-secretary.el

(register-definition-prefixes "org-secretary" '("join" "org-sec-"))


;;; Generated autoloads from org-static-mathjax.el

(register-definition-prefixes "org-static-mathjax" '("org-static-mathjax-"))


;;; Generated autoloads from org-sudoku.el

(register-definition-prefixes "org-sudoku" '("org-sudoku-"))


;;; Generated autoloads from org-toc.el

(autoload 'org-toc-show "org-toc" "\
Show the table of contents of the current Org-mode buffer.

(fn &optional DEPTH POSITION)" t)
(register-definition-prefixes "org-toc" '("org-"))


;;; Generated autoloads from org-track.el

(autoload 'org-track-fetch-package "org-track" "\
Fetch Org package depending on `org-track-fetch-package-extension'.
If DIRECTORY is defined, unpack the package there, i.e. add the
subdirectory org-mode/ to DIRECTORY.

(fn &optional DIRECTORY)" t)
(autoload 'org-track-compile-org "org-track" "\
Compile all *.el files that come with org-mode.
Generate the autoloads file `org-loaddefs.el'.

DIRECTORY is where the directory org-mode/ lives (i.e. the
          parent directory of your local repo.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "org-track" '("org-track-"))


;;; Generated autoloads from org-wikinodes.el

(register-definition-prefixes "org-wikinodes" '("org-wikinodes-"))


;;; Generated autoloads from orgtbl-sqlinsert.el

(register-definition-prefixes "orgtbl-sqlinsert" '("orgtbl-"))


;;; Generated autoloads from ox-bibtex.el

(register-definition-prefixes "ox-bibtex" '("org-bibtex-"))


;;; Generated autoloads from ox-confluence.el

(register-definition-prefixes "ox-confluence" '("org-confluence-"))


;;; Generated autoloads from ox-deck.el

(register-definition-prefixes "ox-deck" '("org-deck-"))


;;; Generated autoloads from ox-extra.el

(register-definition-prefixes "ox-extra" '("org-" "ox-extras"))


;;; Generated autoloads from ox-freemind.el

(autoload 'org-freemind-export-to-freemind "ox-freemind" "\
Export current buffer to a Freemind Mindmap file.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting file should be accessible through
the `org-export-stack' interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don't export
contents of hidden elements.

When optional argument BODY-ONLY is non-nil, only write code
between \"<body>\" and \"</body>\" tags.

EXT-PLIST, when provided, is a property list with external
parameters overriding Org default settings, but still inferior to
file-local settings.

Return output file's name.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)" t)
(register-definition-prefixes "ox-freemind" '("org-freemind-"))


;;; Generated autoloads from ox-groff.el

(register-definition-prefixes "ox-groff" '("org-groff-"))


;;; Generated autoloads from ox-s5.el

(register-definition-prefixes "ox-s5" '("org-s5-"))


;;; Generated autoloads from ox-taskjuggler.el

(autoload 'org-taskjuggler-export "ox-taskjuggler" "\
Export current buffer to a TaskJuggler file.

The exporter looks for a tree with tag that matches
`org-taskjuggler-project-tag' and takes this as the tasks for
this project.  The first node of this tree defines the project
properties such as project name and project period.

If there is a tree with tag that matches
`org-taskjuggler-resource-tag' this tree is taken as resources
for the project.  If no resources are specified, a default
resource is created and allocated to the project.

Also the TaskJuggler project will be created with default reports
as defined in `org-taskjuggler-default-reports'.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

A non-nil optional argument ASYNC means the process should happen
asynchronously.  The resulting file should be accessible through
the `org-export-stack' interface.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don't export
contents of hidden elements.

Return output file's name.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY)" t)
(autoload 'org-taskjuggler-export-and-process "ox-taskjuggler" "\
Export current buffer to a TaskJuggler file and process it.

The exporter looks for a tree with tag that matches
`org-taskjuggler-project-tag' and takes this as the tasks for
this project.  The first node of this tree defines the project
properties such as project name and project period.

If there is a tree with tag that matches
`org-taskjuggler-resource-tag' this tree is taken as resources
for the project.  If no resources are specified, a default
resource is created and allocated to the project.

Also the TaskJuggler project will be created with default reports
as defined in `org-taskjuggler-default-reports'.

If narrowing is active in the current buffer, only export its
narrowed part.

If a region is active, export that region.

When optional argument SUBTREEP is non-nil, export the sub-tree
at point, extracting information from the headline properties
first.

When optional argument VISIBLE-ONLY is non-nil, don't export
contents of hidden elements.

Return a list of reports.

(fn &optional SUBTREEP VISIBLE-ONLY)" t)
(autoload 'org-taskjuggler-export-process-and-open "ox-taskjuggler" "\
Export current buffer to a TaskJuggler file, process and open it.

Export and process the file using
`org-taskjuggler-export-and-process' and open the generated
reports with a browser.

If you are targeting TaskJuggler 2.4 (see
`org-taskjuggler-target-version') the processing and display of
the reports is done using the TaskJuggler GUI.

(fn &optional SUBTREEP VISIBLE-ONLY)" t)
(register-definition-prefixes "ox-taskjuggler" '("org-taskjuggler-"))

;;; End of scraped data

(provide 'org-contrib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-contrib-autoloads.el ends here
