;;; wfnames-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from wfnames.el

(autoload 'wfnames-setup-buffer "wfnames" "\
Initialize wfnames buffer with FILES and display it with DISPLAY-FN.

Arg DISPLAY-FN default to `switch-to-buffer' if unspecified.
When APPEND is specified, append FILES to existing `wfnames-buffer'.

(fn FILES &optional (DISPLAY-FN #\\='switch-to-buffer) APPEND)")
(register-definition-prefixes "wfnames" '("wfnames-"))

;;; End of scraped data

(provide 'wfnames-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wfnames-autoloads.el ends here
