;;; flyspell-correct-helm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flyspell-correct-helm.el

(register-definition-prefixes "flyspell-correct-helm" '("flyspell-correct-helm"))

;;; End of scraped data

(provide 'flyspell-correct-helm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flyspell-correct-helm-autoloads.el ends here
