#+TITLE: Deft layer
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../css/readtheorg.css" />

* Table of Content                                          :TOC_4_org:noexport:
 - [[Description][Description]]
   - [[Differences from default][Differences from default]]
 - [[Install][Install]]
   - [[Layer][Layer]]
   - [[Configuration][Configuration]]
 - [[Key Bindings][Key Bindings]]

* Description
[[http://jblevins.org/projects/deft/][Deft]] is an Emacs mode inspired by =Notational Velocity= for quickly
browsing and creating notes.

** Differences from default
This layer sets the default to use filenames for note titles as well as
=org-mode= for editing. The default extension is =org=. The default
configuration is set to recognize =org=, =md=, and =txt= extensions. If
you prefer that =Deft= recognize other extensions set an alternate
configuration by adding the following in your config file:

#+Begin_SRC emacs-lisp
  (setq deft-extensions '("org" "md" "txt"))  
#+END_SRC

Just add or substitute your preferred extension.

* Install
** Layer
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =deft= to the existing =dotspacemacs-configuration-layers= list in this
file.

** Configuration
By default deft tries to put notes in =~/.deft= but you can change
this like so in your =dotspacemacs/user-config= function:

#+BEGIN_SRC emacs-lisp
(setq deft-directory "~/Dropbox/notes")
#+END_SRC

* Key Bindings

| Key Binding | Description                      |
|-------------+----------------------------------|
| ~SPC a n~   | Open Deft (works globally)       |
| ~SPC m d~   | Delete selected note             |
| ~SPC m r~   | Rename selected note             |
| ~SPC m i~   | Toggle to regex search           |
| ~SPC m n~   | Create new file with filter text |
