#!/usr/bin/env bash
## Script for validating exported(org->sdn) documentation files.
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2018 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

skip_for_branch_update

select_changed_orgs
if [ ${#changed_f_as_args[@]} -ne 0 ]; then
    spacedoc validate -c"./.ci/spacedoc-cfg.edn" /tmp/exported/
    if [ $? -ne 0 ]; then
        echo "Documentation validation failed."
        exit 1
    fi
else
    echo "This commit doesn't change documentation files."
fi
