;;; ledger-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ledger-check.el

(register-definition-prefixes "ledger-check" '("ledger-"))


;;; Generated autoloads from ledger-commodities.el

(register-definition-prefixes "ledger-commodities" '("ledger-"))


;;; Generated autoloads from ledger-complete.el

(register-definition-prefixes "ledger-complete" '("ledger-"))


;;; Generated autoloads from ledger-context.el

(register-definition-prefixes "ledger-context" '("ledger-"))


;;; Generated autoloads from ledger-exec.el

(register-definition-prefixes "ledger-exec" '("ledger-"))


;;; Generated autoloads from ledger-flymake.el

(autoload 'ledger-flymake-enable "ledger-flymake" "\
Enable `flymake-mode' in `ledger-mode' buffers.")
(register-definition-prefixes "ledger-flymake" '("ledger-"))


;;; Generated autoloads from ledger-fontify.el

(register-definition-prefixes "ledger-fontify" '("ledger-fontify-"))


;;; Generated autoloads from ledger-fonts.el

(register-definition-prefixes "ledger-fonts" '("ledger-font-"))


;;; Generated autoloads from ledger-init.el

(register-definition-prefixes "ledger-init" '("ledger-"))


;;; Generated autoloads from ledger-mode.el

(autoload 'ledger-mode "ledger-mode" "\
A mode for editing ledger data files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ledger\\'" . ledger-mode))
(register-definition-prefixes "ledger-mode" '("ledger-"))


;;; Generated autoloads from ledger-navigate.el

(register-definition-prefixes "ledger-navigate" '("ledger-navigate-"))


;;; Generated autoloads from ledger-occur.el

(register-definition-prefixes "ledger-occur" '("ledger-occur"))


;;; Generated autoloads from ledger-post.el

(register-definition-prefixes "ledger-post" '("ledger-"))


;;; Generated autoloads from ledger-reconcile.el

(register-definition-prefixes "ledger-reconcile" '("ledger-"))


;;; Generated autoloads from ledger-regex.el

(register-definition-prefixes "ledger-regex" '("ledger-"))


;;; Generated autoloads from ledger-report.el

(register-definition-prefixes "ledger-report" '("ledger-"))


;;; Generated autoloads from ledger-schedule.el

(register-definition-prefixes "ledger-schedule" '("ledger-"))


;;; Generated autoloads from ledger-sort.el

(register-definition-prefixes "ledger-sort" '("ledger-sort-"))


;;; Generated autoloads from ledger-state.el

(register-definition-prefixes "ledger-state" '("ledger-"))


;;; Generated autoloads from ledger-test.el

(register-definition-prefixes "ledger-test" '("ledger-"))


;;; Generated autoloads from ledger-texi.el

(register-definition-prefixes "ledger-texi" '("ledger-"))


;;; Generated autoloads from ledger-xact.el

(register-definition-prefixes "ledger-xact" '("ledger-"))

;;; End of scraped data

(provide 'ledger-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ledger-mode-autoloads.el ends here
