;;; emacsql-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from emacsql.el

(autoload 'emacsql-show-last-sql "emacsql" "\
Display the compiled SQL of the s-expression SQL expression before point.
A prefix argument causes the SQL to be printed into the current buffer.

(fn &optional PREFIX)" t)
(register-definition-prefixes "emacsql" '("emacsql-"))


;;; Generated autoloads from emacsql-compiler.el

(register-definition-prefixes "emacsql-compiler" '("emacsql-"))


;;; Generated autoloads from emacsql-mysql.el

(register-definition-prefixes "emacsql-mysql" '("emacsql-mysql-"))


;;; Generated autoloads from emacsql-pg.el

(register-definition-prefixes "emacsql-pg" '("emacsql-pg-connection"))


;;; Generated autoloads from emacsql-psql.el

(register-definition-prefixes "emacsql-psql" '("emacsql-psql-"))


;;; Generated autoloads from emacsql-sqlite.el

(register-definition-prefixes "emacsql-sqlite" '("emacsql-sqlite-"))


;;; Generated autoloads from emacsql-sqlite-builtin.el

(register-definition-prefixes "emacsql-sqlite-builtin" '("emacsql-sqlite-builtin-connection"))


;;; Generated autoloads from emacsql-sqlite-common.el

(register-definition-prefixes "emacsql-sqlite-common" '("emacsql-"))


;;; Generated autoloads from emacsql-sqlite-module.el

(register-definition-prefixes "emacsql-sqlite-module" '("emacsql-sqlite-module-connection"))

;;; End of scraped data

(provide 'emacsql-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacsql-autoloads.el ends here
