;;; org-tanglesync-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-tanglesync.el

(autoload 'org-tanglesync-process-buffer-interactive "org-tanglesync" "\
Interactively processes each org src block in a buffer." t)
(autoload 'org-tanglesync-process-buffer-automatic "org-tanglesync" "\
Process each org src block in a buffer without prompt." t)
(register-definition-prefixes "org-tanglesync" '("org-tanglesync-"))

;;; End of scraped data

(provide 'org-tanglesync-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-tanglesync-autoloads.el ends here
