;;; ebib-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ebib.el

(autoload 'ebib "ebib" "\
Ebib, a BibTeX database manager.
Optional argument FILE is a file to load.  If FILE is already
loaded, switch to it.  If KEY is given, jump to it.

(fn &optional FILE KEY)" t)
(autoload 'ebib-init "ebib" "\
Initialise Ebib.
This function sets all variables to their initial values, creates
the buffers and loads the files in `ebib-preload-bib-files'.

This function can be used to open Ebib in the background, e.g.,
in the user's init file.")
(autoload 'ebib-insert-citation "ebib" "\
Insert a citation at POINT.
The user is prompted for a BibTeX key and has to choose one from
the database(s) associated with the current buffer (see
`ebib--get-local-bibfiles' for details), or from the current
database if the current buffer has no associated databases.

If the current buffer is associated with a dependent database,
the entries of its main database are offered as completion
candidates and the entry that is selected is added to the
dependent database if not already there.

This function uses a dedicated completion framework (selectrum,
ivy, helm or ido), if available and active.  It also honors the
option `ebib-citation-insert-multiple'." t)
(register-definition-prefixes "ebib" '("ebib-"))


;;; Generated autoloads from ebib-biblio.el

(autoload 'ebib-biblio-import-doi "ebib-biblio" "\
Fetch a BibTeX entry from a remote server by its DOI using `biblio.el'.
The entry is stored in the current database.

(fn DOI)" t)
(register-definition-prefixes "ebib-biblio" '("ebib-biblio-selection-import"))


;;; Generated autoloads from ebib-db.el

(register-definition-prefixes "ebib-db" '("ebib-"))


;;; Generated autoloads from ebib-filters.el

(register-definition-prefixes "ebib-filters" '("ebib-"))


;;; Generated autoloads from ebib-keywords.el

(register-definition-prefixes "ebib-keywords" '("ebib-"))


;;; Generated autoloads from ebib-notes.el

(register-definition-prefixes "ebib-notes" '("ebib-"))


;;; Generated autoloads from ebib-reading-list.el

(register-definition-prefixes "ebib-reading-list" '("ebib-"))


;;; Generated autoloads from ebib-utils.el

(register-definition-prefixes "ebib-utils" '("ebib-" "with-"))


;;; Generated autoloads from org-ebib.el

(autoload 'org-ebib-open "org-ebib" "\
Open Ebib and jump to ENTRY.

(fn ENTRY)")
(register-definition-prefixes "org-ebib" '("org-ebib-"))

;;; End of scraped data

(provide 'ebib-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ebib-autoloads.el ends here
