#!/usr/bin/env bash
## Script for updating local elpa mirror
##
## Copyright (c) 2012-2014 Sylvain Benner
## Copyright (c) 2014-2020 Sylvain Benner & Contributors
##
## Author: Eugene Yaremenko
## URL: https://github.com/syl20bnr/spacemacs
##
## This file is not part of GNU Emacs.
##
## License: GPLv3

cp "${GITHUB_WORKSPACE}/.github/workflows/scripts/dotspacemacs.el" \
   ~/.spacemacs

ln -s "$(pwd)" $HOME/.emacs.d

mkdir -p "${MIRROR_DIR}"

emacs --batch \
      -l "${HOME}/.emacs.d/init.el" \
      -l "${EM_SCRIPT_PATH}" \
      --eval="(setq elpamr-default-output-directory \"${MIRROR_DIR}\")" \
      --eval="(elpamr-create-mirror-for-installed)"
