#+TITLE: Quick start

* Table of Contents                     :TOC_5_gh:noexport:
- [[#configuration-layers][Configuration layers]]
- [[#dotfile-space-macs][Dotfile (.space-macs)]]
- [[#dotdirectory-space-macsd][Dotdirectory (~/.space-macs.d)]]
- [[#learning-space-macs][Learning Space-macs]]
  - [[#editing-styles][Editing Styles]]
  - [[#the-leader-keys][The leader keys]]
  - [[#evil-tutor][Evil-tutor]]
  - [[#universal-argument][Universal argument]]
  - [[#configuration-layers-and-package-discovery][Configuration layers and Package discovery]]
  - [[#key-bindings-discovery][Key bindings discovery]]
  - [[#describe-functions][Describe functions]]
- [[#how-tos][How-To's]]

* Configuration layers
Space-macs divides its configuration into self-contained units called
=configuration layers=. These layers are stacked on top of each other
to achieve a custom configuration.

By default Space-macs uses a dotfile called =~/.space-macs= to control which
layers to load. Within this file you can also configure certain features.

A configuration layer is a directory containing at least a =packages.el=
file which defines and configures packages to be downloaded from e-macs
package repositories using the =package.el= built-in feature of e-macs.

If you already have your own =e-macs= configuration you can move it to your
own layer.

The following command creates a layer in the =private= directory:

#+BEGIN_EXAMPLE
  SPC SPC configuration-layer/create-layer RET
#+END_EXAMPLE

Any configuration layers you create must be explicitly loaded in =~/.space-macs=.

Note: For your privacy, the contents of the =private= directory are not
under source control. See the section on private configuration management in
the [[https://github.com/syl20bnr/space-macs/blob/develop/doc/DOCUMENTATION.org][documentation]].

* Dotfile (.space-macs)
As mentioned =.space-macs= controls which configuration layers to load and
is also a means to customizing Space-macs.

The following command will create a =.space-macs= file in your home directory:

#+BEGIN_EXAMPLE
  SPC SPC dotspace-macs/install RET
#+END_EXAMPLE

To open the installed dotfile:

#+BEGIN_EXAMPLE
  SPC f e d
#+END_EXAMPLE

To load some configuration layers using the variable
=dotspace-macs-configuration-layers=:

#+BEGIN_SRC elisp
  ;; List of configuration layers to load.
  dotspace-macs-configuration-layers '(auto-completion smex)
#+END_SRC

Some configuration layers support configuration variables to expose granular
control over layer-specific features, [[https://github.com/syl20bnr/space-macs/blob/develop/layers/+source-control/git/README.org][git layer]] being one such example.
Variables can be directly set within =dotspace-macs-configuration-layers= like so:

#+BEGIN_SRC elisp
  ;; List of configuration layers to load.
  dotspace-macs-configuration-layers '(auto-completion
                                      (git :variables
                                           git-magit-status-fullscreen t)
                                      smex)
#+END_SRC

At anytime you can apply the changes made to the dotfile or layers
_without restarting_ Space-macs by pressing ~SPC f e R~.

The [[https://github.com/syl20bnr/space-macs/blob/master/core/templates/.space-macs.template][dotfile template]] contains further information about how to customize
Space-macs. See the dotfile configuration section of the [[https://github.com/syl20bnr/space-macs/blob/develop/doc/DOCUMENTATION.org#dotfile-configuration][documentation]] for
more details.

* Dotdirectory (~/.space-macs.d)
Like =e-macs=, Space-macs initialization can also be contained in an =init.el= file
in a special directory =~/.space-macs.d=. The contents of the dotfile should be
then copied in the =init.el= file.

The e-macs dotfile or dotdirectory is not replaced but rather
complemented by the Space-macs dotfile or dotdirectory. During startup,
e-macs still uses =~/.e-macs.d/init.el= (or =~/.e-macs=) for its
initialization, and variable =user-e-macs-directory= will still point
to =~/.e-macs.d/=, even if =~/.space-macs.d= or =~/.space-macs= are
present. Only now =~/.e-macs.d/init.el= is provided by Space-macs
(e.g. after cloning the Space-macs git repo into an empty
=~/.e-macs.d/=), and your own personal configurations go into
=~/.space-macs.d/init.el= (or =~/.space-macs=).

Have a look into the FAQ for an easy workaround to maintain (your
former) vanilla e-macs and (your new) Space-macs configurations
side-by-side without the need to rename and backup =~/.e-macs.d/=.

* Learning Space-macs
** Editing Styles
Space-macs can be used by Vim users or e-macs users by setting the
=dotspace-macs-editing-style= variable to =vim=, =e-macs= or even =hybrid=
in the dotfile =~/.space-macs=.

** The leader keys
Space-macs key bindings use a leader key which is by default bound to
~SPC~ (space bar) in =vim= or =hybrid= editing styles and ~M-m~ in =e-macs=
style.

You can change it by setting the variable =dotspace-macs-leader-key= if
you use the =vim= style or =dotspace-macs-e-macs-leader-key= if you use
the =e-macs= style (these variables must be set in the file =~/.space-macs=).

For simplicity the documentation always refers to the leader key as
~SPC~.

There is a secondary leader key called the major-mode leader key which is
set to ~​,​~ by default. This key is a shortcut for ~SPC m~
where all the major-mode specific commands are bound.

** Evil-tutor
If you are willing to learn the Vim key bindings (highly recommended since
you can benefit from them even in =e-macs= style), press ~SPC h T v~
to begin an Evil-adapted Vimtutor.

** Universal argument
In =vim= editing style the universal argument defaults to ~SPC u~
instead of ~C-u~ because the latter is used to scroll up as in Vim.

** Configuration layers and Package discovery
By using =helm-space-macs-help= with ~SPC h SPC~ you can quickly search
for a package and get the name of the layers using it.

You can also easily go to the =README.org= of a layer or go to the initialization
function of a package.

** Key bindings discovery
Thanks to [[https://github.com/justbur/e-macs-which-key][which-key]], whenever a prefix command is pressed (like ~SPC~)
a buffer appears after one second listing the possible keys for this prefix.

It is also possible to search for specific key bindings by pressing:

#+BEGIN_EXAMPLE
  SPC ?
#+END_EXAMPLE

To narrow the bindings list to those prefixed with =SPC=,
type a pattern like this regular expression:

#+BEGIN_EXAMPLE
  SPC\ b
#+END_EXAMPLE

which would list all =buffer= related bindings. *Note:* You are at the
/HELM-Descbind/ prompt, the pattern consists of 6 letters: uppercase ~SPC~, a
backslash, an actual space and a lowercase ~b~.

** Describe functions
=Describe functions= are powerful e-macs introspection commands to get information
about functions, variables, modes etc. These commands are bound thusly:

| Key binding | Description       |
|-------------+-------------------|
| ~SPC h d f~ | describe-function |
| ~SPC h d k~ | describe-key      |
| ~SPC h d m~ | describe-mode     |
| ~SPC h d v~ | describe-variable |

* How-To's
Some quick =how-to's= are compiled in the [[https://github.com/syl20bnr/space-macs/blob/develop/doc/FAQ.org#how-do-i][FAQ.]]


