#+TITLE: fasd layer

#+TAGS: layer|tool

* Table of Contents                     :TOC_5_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
  - [[#layer][Layer]]
  - [[#fasd][fasd]]
- [[#comment][Comment]]
- [[#key-bindings][Key bindings]]

* Description
This layer integrates the [[https://github.com/clvv/fasd][fasd]] command line tool into Spacemacs.

** Features:
- Adds easy shortcuts to reference recent files and directories.
- Provides =fasd= with recent open file lists from Emacs.
- Allows to filter =fasd= results with =helm= or =ivy=.

* Install
** Layer
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =fasd= to the existing =dotspacemacs-configuration-layers= list in this
file.

** fasd
[[https://github.com/clvv/fasd][fasd]] must be installed on your system. The general installation
instructions can be found in the repository [[https://github.com/clvv/fasd#install][README]]

On macOS, it can be installed via [[https://github.com/Homebrew/legacy-homebrew][homebrew]]:

#+BEGIN_SRC sh
  $ brew install fasd
#+END_SRC

* Comment
The fasd package has been updated to support Ivy actions (~M-o~). This layer
adds an Ivy action to start a deep search in a directory
(~spacemacs/search-auto~) from the fasd results. After the fasd query,
instead of enter, type ~M-o~ on some directory then press ~s~ to start a
deep search in that directory.

* Key bindings

| Key binding | Description                        |
|-------------+------------------------------------|
| ~SPC f a s~ | find a file or directory with fasd |
| ~SPC f a d~ | find a directory with fasd         |
| ~SPC f a f~ | find a file with fasd              |
