;;; evil-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-command-window.el

(register-definition-prefixes "evil-command-window" '("evil-"))


;;; Generated autoloads from evil-commands.el

(register-definition-prefixes "evil-commands" '("evil-"))


;;; Generated autoloads from evil-common.el

(register-definition-prefixes "evil-common" '("bounds-of-evil-" "evil-" "forward-evil-"))


;;; Generated autoloads from evil-core.el

 (autoload 'evil-mode "evil" nil t)
(register-definition-prefixes "evil-core" '("evil-" "turn-o"))


;;; Generated autoloads from evil-digraphs.el

(autoload 'evil-digraph "evil-digraphs" "\
Convert DIGRAPH to character or list representation.
If DIGRAPH is a list (CHAR1 CHAR2), return the corresponding character;
if DIGRAPH is a character, return the corresponding list.
Searches in `evil-digraphs-table-user' and `evil-digraphs-table'.

(fn DIGRAPH)")
(register-definition-prefixes "evil-digraphs" '("evil-digraphs-table"))


;;; Generated autoloads from evil-ex.el

(register-definition-prefixes "evil-ex" '("evil-"))


;;; Generated autoloads from evil-integration.el

(register-definition-prefixes "evil-integration" '("evil-"))


;;; Generated autoloads from evil-jumps.el

(register-definition-prefixes "evil-jumps" '("evil-"))


;;; Generated autoloads from evil-macros.el

(register-definition-prefixes "evil-macros" '("evil-"))


;;; Generated autoloads from evil-maps.el

(register-definition-prefixes "evil-maps" '("evil-"))


;;; Generated autoloads from evil-repeat.el

(register-definition-prefixes "evil-repeat" '("evil-"))


;;; Generated autoloads from evil-search.el

(register-definition-prefixes "evil-search" '("evil-"))


;;; Generated autoloads from evil-states.el

(register-definition-prefixes "evil-states" '("evil-"))


;;; Generated autoloads from evil-types.el

(register-definition-prefixes "evil-types" '("evil-ex-get-optional-register-and-count"))


;;; Generated autoloads from evil-vars.el

(register-definition-prefixes "evil-vars" '("evil-"))

;;; End of scraped data

(provide 'evil-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-autoloads.el ends here
