# -*- mode: ruby -*-
# vi: set ft=ruby :

# This file is provided for testing this layer - it doesn't really do
# very much!

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision :shell, inline: "echo provisioned"
end
