(require 'sr-speedbar)
(setq sr-speedbar-right-side nil)
(setq sr-speedbar-auto-refresh t)
(setq sr-speedbar-skip-other-window-p t)
(setq speedbar-show-unknown-files t)
(setq speedbar-verbosity-level 0)
(setq speedbar-use-images nil)

(defun sr-speedbar-toggle-and-select ()
  "Toggle the speedbar and give it the focus if it is opened"
  (interactive)
  (sr-speedbar-toggle)
  (if (sr-speedbar-exist-p)
      (lambda ()
        (sr-speedbar-select-window))))
