(require 'yasnippet)
(require 'helm-c-yasnippet)
(setq helm-c-yas-space-match-any-greedy t)
(yas-global-mode t)
(setq yas-prompt-functions '(yas-dropdown-prompt yas-ido-prompt yas-x-prompt))
(setq yas-wrap-around-region 'cua)
(yas-load-directory (concat user-emacs-directory "/snippets"))
