;;; string-edit-at-point-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from string-edit-at-point.el

(autoload 'string-edit-at-point "string-edit-at-point" "\
Pop up a buffer to edit the string at point.
This saves you from needing to manually escape characters." t)
(register-definition-prefixes "string-edit-at-point" '("se/" "string-edit-at-point-"))

;;; End of scraped data

(provide 'string-edit-at-point-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; string-edit-at-point-autoloads.el ends here
