;;; elfeed-tube-mpv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elfeed-tube-mpv.el

(autoload 'elfeed-tube-mpv "elfeed-tube-mpv" "\
Start or seek an mpv session connected to an Elfeed entry.

Call this command with point POS on an Elfeed entry in an Elfeed
Search buffer, or anywhere in an Elfeed Entry, to play the
corresponding video. When called with point in a transcript
segment, seek here or start a new session as appropriate. If a
connected mpv session for a different video is already running
enqueue this video instead.

With prefix argument ARG always start a new, unnconnected mpv
session.

(fn POS &optional ARG)" t)
(autoload 'elfeed-tube-mpv-follow-mode "elfeed-tube-mpv" "\
Follow along with mpv in elfeed-show buffers.

This appliies to Youtube feed entries in Elfeed. When the video
player mpv is started from this buffer (from any location in the
transcript), turning on this minor-mode will cause the cursor to
track the currently playing segment in mpv. You can still click
anywhere in the transcript to seek to that point in the video.

This is a minor mode.  If called interactively, toggle the
`Elfeed-Tube-Mpv-Follow mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `elfeed-tube-mpv-follow-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "elfeed-tube-mpv" '("elfeed-tube-mpv-"))

;;; End of scraped data

(provide 'elfeed-tube-mpv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elfeed-tube-mpv-autoloads.el ends here
