;;; helpful-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helpful.el

(autoload 'helpful-function "helpful" "\
Show help for function named SYMBOL.

See also `helpful-macro', `helpful-command' and `helpful-callable'.

(fn SYMBOL)" t)
(autoload 'helpful-command "helpful" "\
Show help for interactive function named SYMBOL.

See also `helpful-function'.

(fn SYMBOL)" t)
(autoload 'helpful-key "helpful" "\
Show help for interactive command bound to KEY-SEQUENCE.

(fn KEY-SEQUENCE)" t)
(autoload 'helpful-macro "helpful" "\
Show help for macro named SYMBOL.

(fn SYMBOL)" t)
(autoload 'helpful-callable "helpful" "\
Show help for function, macro or special form named SYMBOL.

See also `helpful-macro', `helpful-function' and `helpful-command'.

(fn SYMBOL)" t)
(autoload 'helpful-symbol "helpful" "\
Show help for SYMBOL, a variable, function, macro, or face.

See also `helpful-callable' and `helpful-variable'.

(fn SYMBOL)" t)
(autoload 'helpful-variable "helpful" "\
Show help for variable named SYMBOL.

(fn SYMBOL)" t)
(autoload 'helpful-at-point "helpful" "\
Show help for the symbol at point." t)
(register-definition-prefixes "helpful" '("helpful-"))

;;; End of scraped data

(provide 'helpful-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helpful-autoloads.el ends here
