;;; orgit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from orgit.el

(with-eval-after-load 'magit (keymap-set magit-mode-map "<remap> <org-store-link>" #'orgit-store-link))
(autoload 'orgit-store-link "orgit" "\
Like `org-store-link' but store links to all selected commits, if any.

(fn ARG)" t)
(with-eval-after-load 'org (with-eval-after-load 'magit (org-link-set-parameters "orgit" :store #'orgit-status-store :follow #'orgit-status-open :export #'orgit-status-export :complete #'orgit-status-complete-link)))
(autoload 'orgit-status-store "orgit" "\
Store a link to a Magit-Status mode buffer.
When the region selects one or more commits, then do nothing.
In that case `orgit-rev-store' stores one or more links instead.")
(autoload 'orgit-status-open "orgit" "\


(fn REPO)")
(autoload 'orgit-status-export "orgit" "\


(fn PATH DESC FORMAT)")
(autoload 'orgit-status-complete-link "orgit" "\


(fn &optional ARG)")
(with-eval-after-load 'org (with-eval-after-load 'magit (org-link-set-parameters "orgit-log" :store #'orgit-log-store :follow #'orgit-log-open :export #'orgit-log-export :complete #'orgit-log-complete-link)))
(autoload 'orgit-log-store "orgit" "\
Store a link to a Magit-Log mode buffer.
When the region selects one or more commits, then do nothing.
In that case `orgit-rev-store' stores one or more links instead.")
(autoload 'orgit-log-open "orgit" "\


(fn PATH)")
(autoload 'orgit-log-export "orgit" "\


(fn PATH DESC FORMAT)")
(autoload 'orgit-log-complete-link "orgit" "\


(fn &optional ARG)")
(with-eval-after-load 'org (with-eval-after-load 'magit (org-link-set-parameters "orgit-rev" :store #'orgit-rev-store :follow #'orgit-rev-open :export #'orgit-rev-export :complete #'orgit-rev-complete-link)))
(autoload 'orgit-rev-store "orgit" "\
Store a link to a Magit-Revision mode buffer.

By default store an abbreviated revision hash.

\\<global-map>With a single \\[universal-argument] prefix argument instead store the name of a tag
or branch that points at the revision, if any.  The meaning of this
prefix argument is reversed if `orgit-store-reference' is non-nil.

With a single \\[negative-argument] negative prefix argument store revision using the
form \":/TEXT\", which is described in the gitrevisions(7) manpage.

When more than one prefix argument is used, then `org-store-link'
stores a link itself, without calling this function.

When the region selects one or more commits, e.g., in a log, then
store links to the Magit-Revision mode buffers for these commits.")
(autoload 'orgit-rev-open "orgit" "\


(fn PATH)")
(autoload 'orgit-rev-export "orgit" "\


(fn PATH DESC FORMAT)")
(autoload 'orgit-rev-complete-link "orgit" "\


(fn &optional ARG)")
(register-definition-prefixes "orgit" '("orgit-"))

;;; End of scraped data

(provide 'orgit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; orgit-autoloads.el ends here
