name: Rebase
on:
  push:
    branches: [develop]
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v1
        with:
          base: develop
          repository: syl20bnr/spacemacs
          token: ${{ secrets.GITHUB_TOKEN }}
