name: Automatic Rebase
on:
  issue_comment:
    types: [created]
permissions: {}
jobs:
  rebase:
    permissions:
      contents: write # to push code to rebase (cirrus-actions/rebase)
      pull-requests: read # to get info about PR (cirrus-actions/rebase)

    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.EMACSPACE_PAT }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.EMACSPACE_PAT }}
