on: pull_request
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.1.1
      with:
        changelog_regex: '/CHANGELOG.org'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
