;;; taxy-magit-section-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from taxy-magit-section.el

(register-definition-prefixes "taxy-magit-section" '("taxy-magit-section-"))

;;; End of scraped data

(provide 'taxy-magit-section-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; taxy-magit-section-autoloads.el ends here
