#+TITLE: All The Icons layer

#+TAGS: misc|layer

* Table of Contents                                       :TOC_5_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
- [[#usage][Usage]]

* Description
This layer installs and configures All The Icons.

** Features:
- Enables and configures icons for dired, ivy, and ibuffer when the appropriate layers are enabled.
- Defines icon transformers for ivy-rich.
- Enables icons in company-box.

* Install
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =all-the-icons= to the existing =dotspacemacs-configuration-layers= list in
this file.

After enabling the layer and reloading your configuration (~SPC f e R~), you will
need to install the all-the-icons font by running the
=all-the-icons-install-fonts= command:

#+BEGIN_EXAMPLE
  SPC SPC all-the-icons-install-fonts RET
#+END_EXAMPLE

* Usage
Most of the features provided by this layer work out of the box. However, you'll
need to configure =ivy-rich= yourself.

This layer provides two transformers for customizing =ivy-rich=:
=ivy-rich-buffer-icon= and =ivy-rich-file-icon=. They can be used to iconize
your ivy-rich results as follows.

#+BEGIN_SRC elisp
  (setq ivy-rich-display-transformers-list
        '(ivy-switch-buffer
          (:columns
           ((ivy-rich-buffer-icon (:width 2))
            (ivy-rich-candidate (:width 100))
            (ivy-rich-switch-buffer-indicators (:width 4 :face error :align right))
            (ivy-rich-switch-buffer-project (:width 15 :face success))
            (ivy-rich-switch-buffer-path (:width
                                          (lambda (x)
                                            (ivy-rich-switch-buffer-shorten-path
                                             x (ivy-rich-minibuffer-width 0.3))))))
           :predicate (lambda (cand) (get-buffer cand)))
          counsel-find-file
          (:columns
           ((ivy-read-file-transformer)
            (ivy-rich-counsel-find-file-truename (:face font-lock-doc-face))))
          counsel-M-x
          (:columns
           ((counsel-M-x-transformer (:width 80))
            (ivy-rich-counsel-function-docstring (:face font-lock-doc-face))))
          counsel-describe-function
          (:columns
           ((counsel-describe-function-transformer (:width 40))
            (ivy-rich-counsel-function-docstring (:face font-lock-doc-face))))
          counsel-describe-variable
          (:columns
           ((counsel-describe-variable-transformer (:width 40))
            (ivy-rich-counsel-variable-docstring (:face font-lock-doc-face))))
          counsel-recentf
          (:columns
           ((ivy-rich-file-icon (:width 2))
            (ivy-rich-candidate (:width 0.8))
            (ivy-rich-file-last-modified-time (:face font-lock-comment-face))))
          package-install
          (:columns
           ((ivy-rich-candidate (:width 30))
            (ivy-rich-package-version (:width 16 :face font-lock-comment-face))
            (ivy-rich-package-archive-summary (:width 7 :face font-lock-builtin-face))
            (ivy-rich-package-install-summary (:face font-lock-doc-face))))))
#+END_SRC
