#+TITLE: common-tweaks layer
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../css/readtheorg.css" />

* Table of Contents                                        :TOC_4_org:noexport:
 - [[Description][Description]]
 - [[Install][Install]]
 - [[Tweaks][Tweaks]]
   - [[ct-find-dotfile-no-symlink-confirmation][ct-find-dotfile-no-symlink-confirmation]]
   - [[ct-global-fill-column-indicator-mode][ct-global-fill-column-indicator-mode]]
   - [[ct-helm-no-dots][ct-helm-no-dots]]
   - [[ct-helm-yas-in-hippie-expand][ct-helm-yas-in-hippie-expand]]
   - [[ct-neotree-close-on-open][ct-neotree-close-on-open]]
   - [[ct-neotree-collapse-on-parent][ct-neotree-collapse-on-parent]]
   - [[ct-persistent-undo][ct-persistent-undo]]
   - [[ct-python-underscore-in-word][ct-python-underscore-in-word]]
   - [[ct-space-dot-C-c][ct-space-dot-C-c]]
   - [[ct-space-dot-evil-ex][ct-space-dot-evil-ex]]

* Description
This layer allows to easily enable some common Spacemacs tweaks.

* Install
To use this contribution add it to your =~/.spacemacs=:

#+begin_src emacs-lisp
(setq-default dotspacemacs-configuration-layers '(common-tweaks))
#+end_src

This layer has no effect until some tweaks are enable through variables:

#+begin_src emacs-lisp
(setq-default dotspacemacs-configuration-layers '((common-tweaks
                                                     :variables
                                                     ct-neotree-close-on-open t
                                                     ct-neotree-collapse-on-parent t
                                                     ...
                                                     )))
#+end_src

* Tweaks

The following tweaks are available:

** ct-find-dotfile-no-symlink-confirmation
Prevent asking for symlink confirmation when loading the =dotspacemacs=.

** ct-global-fill-column-indicator-mode
Turn on the fill column indicator globally (all =prog-mode= and =text-mode=).

** ct-helm-no-dots
Remove dots (=.= and =..=) from helm files buffer.

** ct-helm-yas-in-hippie-expand
Add helm-yas as a hippie-expand function.

** ct-neotree-close-on-open
Close the neotree window when a file is opened from it.

** ct-neotree-collapse-on-parent
Collapse the neotree hierarchy when going on a parent node.

** ct-persistent-undo
Enable persistent undo between emacs sessions.

** ct-python-underscore-in-word
Make underscore part of =word= text objects in =python-mode=.

** ct-space-dot-C-c
Provide all =C-c C-[a-z]= bindings on the =SPC .= prefix.
Can't be used at the same time as other =ct-space-dot= variables.

** ct-space-dot-evil-ex
Provide some =evil-ex= bindings on the ~SPC .~ prefix.
Can't be used at the same time as other =ct-space-dot= variables.
